// This file is meant to be used with daalbot events with the "messageCreate" trigger in order to automatically delete and warn the user who sent it
// DO NOT EDIT THIS FILE -- ANY CHANGE IN ITS HASH WILL RESULT IN IT NO LONGER FUNCTIONING
let LIST_DATA = '';

const axios = util.libraries.load('axios');
const resp = axios.get('https://cdn.jsdelivr.net/gh/NotPiny/Data/discord/phishing/servers.txt');
LIST_DATA = resp.data;

const unsafeInvites = LIST_DATA.split(',');

function findDiscordInvites(message) {
    const regex = /(?:https?:\/\/)?(?:www\.)?(?:discord\.gg\/|discordapp\.com\/invite\/|discord\.com\/invite\/)([a-zA-Z0-9]+)/g;
    const invites = [];
    let match;
    
    while ((match = regex.exec(message)) !== null) {
        invites.push({
            fullMatch: match[0],  // The entire matched string
            inviteCode: match[1]  // Just the invite code
        });
    }
    
    return invites;
}

const invites = findDiscordInvites(message.content);

if (invites.find(invite => unsafeInvites.includes(invite.inviteCode))) {
	message.delete();

	try {
		message.author.send(`Hey, you just sent a phishing link within the \`${message.guild.name}\` server. All we've done is delete your message but we still **strongly advise that you change your discord login**, if possible do this from another device such as your phone. You should also reinstall your operating system if you ran any programs/files (its better to be safe than sorry)`)
	} catch {} // DMs disabled probably
}
